const images = {
  default_img: 'http://deshpro.b0.upaiyun.com/deshpro_public/default_img.png',
  ios_app: '/images/ios_app.png',
  andorid: '/images/andorid.png',
  download_close: '/images/download_close.png',
  empty_image: '/images/empty_ticket.png',
  cart: '/images/cart.png',
  is: '/images/is>.png',
  Android: '/images/Android.png',
  iPhone: '/images/iPhone.png',
  safari: '/images/safari12.png',
  load_yaoqing: '/images/load_yaoqing.png',
  bottomarea: '/images/bottomarea.png',
  sign_close_gray: '/images/sign_close_one.png',
  sign_eye_open: '/images/sign_eye_open.png',
  sign_eye: '/images/sign_eye.png',
  croup_receive: '/images/croup_receive.png',
  like_gray: '/images/like_gray.png',
  home_avatar: '/images/home_avatar.png',
  reply: '/images/reply.png',
  bg_music: '/images/bg_music.png',
  bg_music_close: '/images/bg_music_close.png',
  sign_return: '/images/sign_retrun.png',
  gray_home: '/images/navigation/gray_home.png',
  red_home: '/images/navigation/red_home.png',
  gray_explore: '/images/navigation/gray_explore.png',
  red_explore: '/images/navigation/red_explore.png',
  cny: '/images/cny.png',
  hkd: '/images/hkd.png',
  mop: '/images/mop.png',
  one1: '/images/one1.png',
  two: '/images/two.png',
  three: '/images/three.png',
  adr_right: '/images/adr_right.png',
  right: '/images/is>.png',
  sign_retrun: '/images/sign_retrun.png',

  macau: {
    search: '/images/macau/search.png',
    book: '/images/macau/book.png',
    entertainment: '/images/macau/entertainment.png',
    food: '/images/macau/food.png',
    gift: '/images/macau/gift.png',
    hotel: '/images/macau/hotel.png',
    rate_exchange: '/images/macau/rate_exchange.png',
    store: '/images/macau/store.png',
    viewpoint: '/images/macau/viewpoint.png',
    location: '/images/macau/location.png',
    call: '/images/macau/call.png',
    rate1: '/images/macau/rate1.png',
    rate2: '/images/macau/rate2.png',
    down: '/images/macau/down.png',
    down2: '/images/macau/down2.png',
    night: '/images/macau/night.png',
    right: '/images/macau/right.png',
    star: '/images/macau/star.png',
    up: '/images/macau/up.png',
    price1: '/images/macau/price1.png',
    price2: '/images/macau/price2.png',
    price1_red: '/images/macau/price1_red.png',
    price2_red: '/images/macau/price2_red.png',
    callPhone: '/images/macau/callPhone.png',
    notRoom: '/images/macau/notRoom.png',
    bg_music: '/images/macau/bg_music.png',
    bg_music_close: '/images/macau/bg_music_close.png'
  },
  navigation2: {
    weather: '/images/navigation/weather.png',
    round_trip: '/images/navigation/round_trip.png',
    fast_food: '/images/navigation/fast_food.png',
    convenient: '/images/navigation/convenient.png',
    hotline: '/images/navigation/hotline.png',
    hotel_bg:'/images/navigation/hotel_bg.png',
    info_ng:'/images/navigation/info_ng.png',
    mall_bg:'/images/navigation/mall_bg.png',
    raiders_bg:'/images/navigation/raiders_bg.png',
    rate_bg:'/images/navigation/rate_bg.png',
    rec_bg:'/images/navigation/rec_bg.png',
    shop_bg:'/images/navigation/shop_bg.png',
    visa:'/images/navigation/visa.png',
    tehui:'/images/navigation/tehui.png',
    coupon_bg:'/images/navigation/coupon_bg.png',
    car_bg:'/images/navigation/car_bg.png'
  },
  social: {
    like_gray: '/images/social/like_gray.png',
    more_3: '/images/social/more_3.png',
    article_delete: '/images/social/delete.png',
    like_red: '/images/social/like_red.png',
    comment_gray: '/images/social/comment_gray.png'
  },
  fastBtn: {
    round1: '/images/fastBtn/round1.jpeg',
    round2: '/images/fastBtn/round2.jpeg',
    round3: '/images/fastBtn/round3.jpeg',
    round4: '/images/fastBtn/round4.jpeg',
    round5: '/images/fastBtn/round5.jpeg',
    round6: '/images/fastBtn/round6.jpeg'
  },

  out_exit: '/images/out_exit.png'
}
export default images
